services:
  - type: web
    name: amazon-scraper-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CACHE_TTL_MINUTES
        value: 30
      - key: JOB_TIMEOUT_MINUTES
        value: 10
      - key: MAX_CONCURRENT_JOBS
        value: 2
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/.cache/puppeteer

